[package]
name = "aoc2024"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0", default-features = false }
rayon = { version = "1.0", default-features = false }
regex = { version = "1.0", default-features = false, features = ["default"] }
